name: Build nonraid-dkms Debian Package

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub release'
        required: false
        default: false
        type: boolean
      draft_release:
        description: 'Create release as draft (no tag)'
        required: false
        default: false
        type: boolean

env:
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build-artifact:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get dkms version
        id: get-dkms
        run: |
          # Get the version from the dkms.conf
          VERSION=$(grep PACKAGE_VERSION= dkms.conf | cut -d= -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get Next Build Number
        id: get-build
        run: |
          NEXT_BUILD=$(git tag -l "nonraid-dkms-${{ steps.get-dkms.outputs.version }}-*" | wc -l)
          NEXT_BUILD=$((NEXT_BUILD + 1))
          echo "build=$NEXT_BUILD" >> $GITHUB_OUTPUT

      - name: Install Debian Package Building Dependencies
        run: sudo bash debian/install_pkg_build_deps.sh

      - name: Create Debian Package
        run: |
          sed -i "s/1.0.0-1/${{ steps.get-dkms.outputs.version }}-${{ steps.get-build.outputs.build }}/" debian/changelog
          make clean package

      - name: Workaround actions/upload-artifact#176
        run: |
          echo "artifacts_path=$(realpath ..)" >> $GITHUB_ENV

      - name: Upload Debian Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nonraid-dkms-${{ steps.get-dkms.outputs.version }}-${{ steps.get-build.outputs.build }}
          path: |
            ${{ env.artifacts_path }}/nonraid-dkms_*.deb
            ${{ env.artifacts_path }}/nonraid-dkms_*.changes
            ${{ env.artifacts_path }}/nonraid-dkms_*.buildinfo
          retention-days: 30

      - name: Get Commits Since Last Release
        id: get-commits
        if: github.event.inputs.create_release == 'true'
        run: |
          LAST_DKMS_TAG=$(git tag -l "nonraid-dkms-*" --sort=-committerdate | head -n1 || echo "none")
          if [ "$LAST_DKMS_TAG" = "none" ]; then
            # If no nonraid-dkms tags exist, get all commits
            COMMITS=$(git log --pretty=format:"- %s (%h)" -- md_nonraid/ raid6/ docs/ debian/)
          else
            # Get commits since the last nonraid-dkms tag
            COMMITS=$(git log ${LAST_DKMS_TAG}..HEAD --pretty=format:"- %s (%h)" -- md_nonraid/ raid6/ docs/ debian/ Makefile dkms.conf)
          fi
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.event.inputs.create_release == 'true'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.draft_release != 'true' && format('nonraid-dkms-{0}-{1}', steps.get-dkms.outputs.version, steps.get-build.outputs.build) || '' }}
          draft: ${{ github.event.inputs.draft_release }}
          name: NonRAID DKMS Debian Package - Version ${{ steps.get-dkms.outputs.version }} Build ${{ steps.get-build.outputs.build }}
          body: |
            **NonRAID DKMS Package - Version ${{ steps.get-dkms.outputs.version }} Build ${{ steps.get-build.outputs.build }}**

            This release contains the NonRAID kernel driver DKMS package for Ubuntu/Debian systems.
            ${{ github.event.inputs.draft_release == 'true' && format('
            > ⚠️ **DRAFT RELEASE** - This is a draft release without an associated Git tag. Finalize this release before tagging as:
            > `nonraid-dkms-{0}-{1}`', steps.get-dkms.outputs.version, steps.get-build.outputs.build) || '' }}

            ## What's Included
            - `nonraid-dkms` package with kernel module source and build scripts
            - Compatible with kernel versions **6.1 - 6.8** and **6.11 and later** (tested up to 6.14) (6.9 and 6.10 are not supported)
            - Tested on Ubuntu 24.04 LTS (with GA kernel 6.8 and HWE kernels 6.11, 6.14) and Debian 12 (with kernel 6.1)

            ## Changes Since Last Release
            ${{ steps.get-commits.outputs.commits }}

            ## Installation
            ```bash
            sudo apt install dkms linux-headers-$(uname -r) build-essential
            sudo apt install ./nonraid-dkms_*.deb
            sudo update-initramfs -u -k all
            # Reboot required
            ```

            ## Usage
            After installation and reboot, load the driver:
            ```bash
            sudo modprobe nonraid super=/path/to/nonraid.dat
            ```

            ## Important Notes
            - ⚠️ **Experimental software** - Use at your own risk
            - You should also download & install the latest [nonraid-tools package](https://github.com/qvr/nonraid/releases?q=nonraid+tools) from separate release for array management `nmdctl` tool.
            - See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for detailed usage instructions
            - Always backup important data before use
          files: |
            ../*.deb
